//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Controles.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Controles: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""PajarosVcerdos"",
            ""id"": ""ff2a1dd3-7be0-4b40-91d4-cf56d24d69cb"",
            ""actions"": [
                {
                    ""name"": ""Presionado"",
                    ""type"": ""Button"",
                    ""id"": ""30c4347a-adc4-46a0-8b62-3c54d4408c3a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pow"",
                    ""type"": ""Value"",
                    ""id"": ""aab865aa-848f-4dff-a3e7-6d49d35bd5f5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Potenciamas"",
                    ""type"": ""Button"",
                    ""id"": ""41f4ec4a-cc3e-4383-8f7c-c5b9c35aafc4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Posicion"",
                    ""type"": ""Value"",
                    ""id"": ""69c9e6fe-8e16-4288-9dc5-454cab3d5c7b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9a7c6d9a-c620-4ddb-8920-e4094967a62e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Presionado"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77a09357-6fbd-43df-8979-7ffdd3fc3be6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4998fd46-9d71-40e7-9d06-9088600dcddb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Potenciamas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fc6e6bb-d2cc-43c3-89c7-a93b7b96043a"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Posicion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PajarosVcerdos
        m_PajarosVcerdos = asset.FindActionMap("PajarosVcerdos", throwIfNotFound: true);
        m_PajarosVcerdos_Presionado = m_PajarosVcerdos.FindAction("Presionado", throwIfNotFound: true);
        m_PajarosVcerdos_Pow = m_PajarosVcerdos.FindAction("Pow", throwIfNotFound: true);
        m_PajarosVcerdos_Potenciamas = m_PajarosVcerdos.FindAction("Potenciamas", throwIfNotFound: true);
        m_PajarosVcerdos_Posicion = m_PajarosVcerdos.FindAction("Posicion", throwIfNotFound: true);
    }

    ~@Controles()
    {
        UnityEngine.Debug.Assert(!m_PajarosVcerdos.enabled, "This will cause a leak and performance issues, Controles.PajarosVcerdos.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PajarosVcerdos
    private readonly InputActionMap m_PajarosVcerdos;
    private List<IPajarosVcerdosActions> m_PajarosVcerdosActionsCallbackInterfaces = new List<IPajarosVcerdosActions>();
    private readonly InputAction m_PajarosVcerdos_Presionado;
    private readonly InputAction m_PajarosVcerdos_Pow;
    private readonly InputAction m_PajarosVcerdos_Potenciamas;
    private readonly InputAction m_PajarosVcerdos_Posicion;
    /// <summary>
    /// Provides access to input actions defined in input action map "PajarosVcerdos".
    /// </summary>
    public struct PajarosVcerdosActions
    {
        private @Controles m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PajarosVcerdosActions(@Controles wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PajarosVcerdos/Presionado".
        /// </summary>
        public InputAction @Presionado => m_Wrapper.m_PajarosVcerdos_Presionado;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVcerdos/Pow".
        /// </summary>
        public InputAction @Pow => m_Wrapper.m_PajarosVcerdos_Pow;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVcerdos/Potenciamas".
        /// </summary>
        public InputAction @Potenciamas => m_Wrapper.m_PajarosVcerdos_Potenciamas;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVcerdos/Posicion".
        /// </summary>
        public InputAction @Posicion => m_Wrapper.m_PajarosVcerdos_Posicion;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PajarosVcerdos; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PajarosVcerdosActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PajarosVcerdosActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PajarosVcerdosActions" />
        public void AddCallbacks(IPajarosVcerdosActions instance)
        {
            if (instance == null || m_Wrapper.m_PajarosVcerdosActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PajarosVcerdosActionsCallbackInterfaces.Add(instance);
            @Presionado.started += instance.OnPresionado;
            @Presionado.performed += instance.OnPresionado;
            @Presionado.canceled += instance.OnPresionado;
            @Pow.started += instance.OnPow;
            @Pow.performed += instance.OnPow;
            @Pow.canceled += instance.OnPow;
            @Potenciamas.started += instance.OnPotenciamas;
            @Potenciamas.performed += instance.OnPotenciamas;
            @Potenciamas.canceled += instance.OnPotenciamas;
            @Posicion.started += instance.OnPosicion;
            @Posicion.performed += instance.OnPosicion;
            @Posicion.canceled += instance.OnPosicion;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PajarosVcerdosActions" />
        private void UnregisterCallbacks(IPajarosVcerdosActions instance)
        {
            @Presionado.started -= instance.OnPresionado;
            @Presionado.performed -= instance.OnPresionado;
            @Presionado.canceled -= instance.OnPresionado;
            @Pow.started -= instance.OnPow;
            @Pow.performed -= instance.OnPow;
            @Pow.canceled -= instance.OnPow;
            @Potenciamas.started -= instance.OnPotenciamas;
            @Potenciamas.performed -= instance.OnPotenciamas;
            @Potenciamas.canceled -= instance.OnPotenciamas;
            @Posicion.started -= instance.OnPosicion;
            @Posicion.performed -= instance.OnPosicion;
            @Posicion.canceled -= instance.OnPosicion;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PajarosVcerdosActions.UnregisterCallbacks(IPajarosVcerdosActions)" />.
        /// </summary>
        /// <seealso cref="PajarosVcerdosActions.UnregisterCallbacks(IPajarosVcerdosActions)" />
        public void RemoveCallbacks(IPajarosVcerdosActions instance)
        {
            if (m_Wrapper.m_PajarosVcerdosActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PajarosVcerdosActions.AddCallbacks(IPajarosVcerdosActions)" />
        /// <seealso cref="PajarosVcerdosActions.RemoveCallbacks(IPajarosVcerdosActions)" />
        /// <seealso cref="PajarosVcerdosActions.UnregisterCallbacks(IPajarosVcerdosActions)" />
        public void SetCallbacks(IPajarosVcerdosActions instance)
        {
            foreach (var item in m_Wrapper.m_PajarosVcerdosActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PajarosVcerdosActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PajarosVcerdosActions" /> instance referencing this action map.
    /// </summary>
    public PajarosVcerdosActions @PajarosVcerdos => new PajarosVcerdosActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PajarosVcerdos" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PajarosVcerdosActions.AddCallbacks(IPajarosVcerdosActions)" />
    /// <seealso cref="PajarosVcerdosActions.RemoveCallbacks(IPajarosVcerdosActions)" />
    public interface IPajarosVcerdosActions
    {
        /// <summary>
        /// Method invoked when associated input action "Presionado" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPresionado(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Pow" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPow(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Potenciamas" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPotenciamas(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Posicion" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosicion(InputAction.CallbackContext context);
    }
}
